[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
caller = "5mxTodrpcpXz6Ani2UeE97FfyVSEY75JFcyTRWHnaztW"
solana_coverage = "2mSfrzvHWwY1waEPtPNmdp3R1rESxmp6rx4ZhEUSVSJh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/lyubo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
